require("vim-options")
require("config.lazy")
require("config.keybinds")
require("telescope").load_extension("ui-select")
require("telescope").load_extension("project")
require("config.alpha-config")
