require("vim-options")
require("config.filetype")
require("config.lazy")
require("config.keybinds")
require("telescope").load_extension("ui-select")
require("telescope").load_extension("project")
require("config.alpha-config")
vim.api.nvim_set_hl(0, "CopilotChatHeader", { fg = "#7C3AED", bold = true })
vim.api.nvim_set_hl(0, "CopilotChatSeparator", { fg = "#374151" })
